[manifest]
id = "any_craft"
version = "2.0.0"
display_name = "Any Craft, Any Mission"
description = "The hangar lets you fly any standard craft (X-wing, Y-wing, A-wing, V-wing, Snowspeeder, Millennium Falcon, TIE Interceptor) on any mission. Nothing is unlocked in your save. Snowspeeder missions may be unwinnable in other craft."
short_description = "Fly any standard craft on any mission."
authors = ["RogueSquadron64Recomp"]
game_id = "rs64"
minimum_recomp_version = "0.0.0"

[inputs]
elf_path = "build/mod.elf"
mod_filename = "any_craft"
func_reference_syms_file = "../../syms/rogue_squadron.syms.toml"
data_reference_syms_files = [ "../../syms/rogue_squadron.datasyms.toml" ]
