# cmake -DPLATFORM=desktop [-DRECOMP_MOD_TOOL=<path>] [-DMIPS_GCC=<path> -DMIPS_LD=<path> | -DMIPS_TOOLCHAIN_DIR=<dir>] -P build_code_mods.cmake
# Builds every .nrm that mods/platforms.json lists for PLATFORM, from the mods/<dir> whose mod.toml has a matching mod_filename.
if (NOT PLATFORM)
    message(FATAL_ERROR "build_code_mods.cmake needs PLATFORM")
endif()
set(MODS_DIR "${CMAKE_CURRENT_LIST_DIR}/../../mods")
file(READ "${MODS_DIR}/platforms.json" manifest)
string(JSON count ERROR_VARIABLE err LENGTH "${manifest}" "${PLATFORM}")
if (err)
    message(FATAL_ERROR "mods/platforms.json has no \"${PLATFORM}\" list: ${err}")
endif()

set(forward "")
foreach(var RECOMP_MOD_TOOL MIPS_GCC MIPS_LD MIPS_TOOLCHAIN_DIR)
    if (DEFINED ${var})
        list(APPEND forward "-D${var}=${${var}}")
    endif()
endforeach()

file(GLOB mod_tomls "${MODS_DIR}/*/mod.toml")
math(EXPR last "${count} - 1")
foreach(i RANGE ${last})
    string(JSON entry GET "${manifest}" "${PLATFORM}" ${i})
    if (NOT entry MATCHES "\\.nrm$")
        continue()
    endif()
    string(REGEX REPLACE "\\.nrm$" "" nrm_name "${entry}")

    set(mod_dir "")
    foreach(toml ${mod_tomls})
        file(STRINGS "${toml}" hit REGEX "^mod_filename *= *\"${nrm_name}\"")
        if (hit)
            get_filename_component(mod_dir "${toml}" DIRECTORY)
            break()
        endif()
    endforeach()
    if (NOT mod_dir)
        message(FATAL_ERROR "platforms.json lists ${entry}, but no mods/*/mod.toml has mod_filename = \"${nrm_name}\"")
    endif()

    message(STATUS "Building ${entry} from ${mod_dir}")
    execute_process(COMMAND ${CMAKE_COMMAND} -S "${mod_dir}" -B "${mod_dir}/build" ${forward} RESULT_VARIABLE rc)
    if (rc EQUAL 0)
        execute_process(COMMAND ${CMAKE_COMMAND} --build "${mod_dir}/build" --config Release RESULT_VARIABLE rc)
    endif()
    if (NOT rc EQUAL 0)
        message(FATAL_ERROR "Building ${entry} failed")
    endif()
endforeach()
