# cmake -DSRC=<repo mods dir> -DDST=<staged mods dir> -DPLATFORM=desktop -P stage_mods.cmake
# Copies the mods mods/platforms.json lists for PLATFORM into DST (an empty DST is a no-op, for config-gated callers). User mod folders
# already in DST are left alone; staged .nrm files are cleared first so a renamed or dropped code mod can't linger (two copies of one mod
# conflict and block game start).
if (NOT DST)
    return()
endif()
if (NOT SRC OR NOT PLATFORM)
    message(FATAL_ERROR "stage_mods.cmake needs SRC and PLATFORM")
endif()
file(READ "${SRC}/platforms.json" manifest)
string(JSON count ERROR_VARIABLE err LENGTH "${manifest}" "${PLATFORM}")
if (err)
    message(FATAL_ERROR "mods/platforms.json has no \"${PLATFORM}\" list: ${err}")
endif()
file(MAKE_DIRECTORY "${DST}")
file(GLOB staged_nrm "${DST}/*.nrm")
if (staged_nrm)
    file(REMOVE ${staged_nrm})
endif()
if (count EQUAL 0)
    return()
endif()
math(EXPR last "${count} - 1")
foreach(i RANGE ${last})
    string(JSON name GET "${manifest}" "${PLATFORM}" ${i})
    if (EXISTS "${SRC}/${name}")
        file(COPY "${SRC}/${name}" DESTINATION "${DST}")
    else()
        message(WARNING "mods/platforms.json lists \"${name}\" for ${PLATFORM}, but mods/${name} does not exist (code mods must be built first)")
    endif()
endforeach()
